name: Benchmark

on:
  push:
    branches: ["master"]
    paths:
      - "crates/nisba/**"
      - "crates/nisbac/**"
      - "benches/**"
      - ".github/workflows/bench.yml"
  pull_request:
    branches: ["master"]
    paths:
      - "crates/nisba/**"
      - "crates/nisbac/**"
      - "benches/**"
      - ".github/workflows/bench.yml"
  workflow_dispatch:

jobs:
  bench:
    name: Run Benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Download protoc
        run: curl -L https://github.com/protocolbuffers/protobuf/releases/download/v35.1/protoc-35.1-linux-x86_64.zip -o protoc.zip

      - name: Unzip protoc
        run: unzip protoc.zip -d protoc

      - name: Add protoc to PATH
        run: echo "$(pwd)/protoc/bin" >> $GITHUB_PATH

      - name: Run benchmarks
        run: cargo bench

      - name: Upload criterion report
        uses: actions/upload-artifact@v7
        with:
          name: criterion-report
          path: target/criterion
